name: Deploy to GitHub Pages

on:
  push:
    branches:
      - test-branch 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  

      - name: Configure Git
        run: |
            git config --global user.name "tkakar"
            git config --global user.email "tkakar@wpi.edu"
  

      - name: Install pnpm
        run: |
          npm install -g pnpm

      - name: Install dependencies
        run: |
          pnpm install

      - name: Build the project
        run: |
          pnpm run build  # This runs the docusaurus build command

      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          pnpm run deploy