name: Deploy to GitHub Pages

on:
  push:
    branches:
      - test-branch 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  

      - name: Install pnpm
        run: |
          npm install -g pnpm

      - name: Install dependencies
        run: |
          pnpm install

      - name: Build the project
        run: |
          pnpm run build  # This runs the docusaurus build command

      - name: Deploy to GitHub Pages
        run: |
          pnpm run deploy  # This runs the gh-pages deploy command
